### PR TITLE
scripts and some doku

### PR DESCRIPTION
**Pull request by dev-foo-bar**
Hello,
thanks for writing this program. You gave me the glue for controlling my linux based desktop(s) with Home Assistant. I added some scripts and some documentation about the scripts. I'd try to reduce the load of every script to the bare minimum. It would be kind if you merge this to your repo. 

Kind Regards
dev-foo-bar

P.S.: Unfortunately I am not a go developer and this is one of my first contributions.

### CODE REVIEW

**Comment by W-Floyd** [comment]
Thanks so much! I took a quick look over and everything seems reasonable, though I haven't tested myself. Seeing as this doesn't modify anything, I'm happy to merge and sort out any issues later. Thanks for the documentation too!

**Comment by W-Floyd** [comment]
If it's convenient, a sample config with the scripts in use would be a welcome addition. Not worries if not though!

**Comment by dev-foo-bar** [comment]
Hi,
thank for merging. Samples for the config are on the way. At the moment, i work on a way to make the install a little bit more convenient. During this way, I see a possibility to create the configuration dynamically (based on the hardware, ha-mqtt-iot is enrolled on). 

Kind regards
dev-foo-bar

**Comment by W-Floyd** [comment]
That could be an option. In the past (before I rewrote everything) I had a couple built in entity types that could just be turned on, battery sensors and laptop display if I remember correctly. An automatic config generator would also be perfectly viable.

Part of the benefit of the built-in entities was that I could make them platform independent (rather, I would write platform specific code so the config was independant)

**Pull request merged**
